# Generated by Django 6.1.1 on 2026-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='🍴', max_length=10)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
    ]
