# Generated by Django 6.1.1 on 2026-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_recipe_image_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
