# Generated by Django 6.1.1 on 2026-09-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('soups', '🍲 Супы'), ('meat', '🍖 Мясные блюда'), ('chicken', '🍗 Курица'), ('fish', '🐟 Рыба'), ('salads', '🥗 Салаты'), ('pasta', '🍝 Паста'), ('baking', '🍕 Выпечка'), ('desserts', '🍰 Десерты'), ('breakfast', '🥞 Завтраки'), ('drinks', '🥤 Напитки'), ('rice', '🍚 Рисовые блюда')], default='soups', max_length=20),
        ),
    ]
